k8s_install_version: "v1.34"
k8s_patch_version: "0"
k8s_install_version_semver: "{{ k8s_install_version }}.{{ k8s_patch_version }}"

kubeadm_version: "{{ k8s_install_version_semver | replace('v', '') }}-*"
kubelet_version: "{{ k8s_install_version_semver | replace('v', '') }}-*"
kubectl_version: "{{ k8s_install_version_semver | replace('v', '') }}-*"

tailscale_enabled: true