# kubectl bash completion 및 alias 설정
- name: bash-completion 패키지 설치
  become: true
  ansible.builtin.apt:
    name: bash-completion
    state: present


- name: ~/.bashrc 에 kubectl 자동완성 / alias 설정 추가
  become: false
  ansible.builtin.blockinfile:
    path: "~/.bashrc"
    create: true
    mode: '0644'
    marker: "# {mark} ANSIBLE MANAGED BLOCK - kubectl"
    block: |
      source <(kubectl completion bash)
      alias k=kubectl
      complete -o default -F __start_kubectl k
