- name: calico CNI 설치
  become: true
  block:
    - name: role_path 출력
      debug:
        msg: "role_path: {{ role_path }}"
        
    - name: Calico manifest 파일 복사
      copy:
        src: "{{ role_path }}/files/{{ calico_manifest_name }}-{{ calico_manifest_version }}.yaml"
        dest: /tmp/{{ calico_manifest_name }}-{{ calico_manifest_version }}.yaml

    - name: Calico CNI 적용
      command: >
        kubectl --kubeconfig /etc/kubernetes/admin.conf apply -f /tmp/{{ calico_manifest_name }}-{{ calico_manifest_version }}.yaml