- name: Hostname Change
  hosts: k8s_group
  roles:
    - roles/hostname_change

- name: hosts 파일 수정
  hosts: k8s_group
  become: true
  gather_facts: false
  tasks:
    - name: 모든 노드의 외부 IP와 hostname 매핑
      lineinfile:
        path: /etc/hosts
        line: "{{ hostvars[item]['ansible_host'] }} {{ hostvars[item]['hostname'] }}"
        state: present
        backup: true
      loop: "{{ groups['controlplane_group'] + groups['worker_group'] }}"