- name: vm 초기 설정
  import_playbook: init/playbook-edit-vm.yaml


- name: Install Common Components
  hosts: k8s_group
  roles:
    - roles/install_k8s_components


- name: ControlPlane Init
  hosts: controlplane_1
  roles:
    - roles/kubeadm_init


# - name: CNI Install (Flannel)
#   hosts: controlplane_1
#   roles:
#     - roles/cni_flannel

- name: CNI Install (Calico)
  hosts: controlplane_1
  roles:
    - roles/cni_calico


- name: Worker Join
  hosts: worker_group
  roles:
    - roles/worker_join