all:
  children:
    k8s_group:
      children:
        controlplane_group:
        worker_group:
    controlplane_group:
      hosts:
        controlplane_1:
          ansible_host: '100.97.236.79'
          hostname: controlplane-1
          ansible_user: 'ubuntu'
          ansible_ssh_private_key_file: '~/.ssh/nhncloud-ms.pem'
          # ansible_ssh_pass: 'ubuntu'
    worker_group:
      hosts:
        worker_1:
          ansible_host: '100.115.163.86'
          hostname: worker-1
          ansible_user: 'ubuntu'
          ansible_ssh_private_key_file: '~/.ssh/nhncloud-ms.pem'
          # ansible_ssh_pass: 'ubuntu'