all:
  children:
    k8s_group:
      children:
        controlplane_group:
        worker_group:
    controlplane_group:
      hosts:
        controlplane_1:
          ansible_host: '100.83.140.26'
          hostname: test-controlplane-1
          ansible_user: 'ubuntu'
          ansible_ssh_private_key_file: '~/.ssh/nhncloud-letomok.pub'
          # ansible_ssh_pass: 'ubuntu'
    worker_group:
      hosts:
        worker_1:
          ansible_host: '100.65.95.10'
          hostname: test-worker-1
          ansible_user: 'ubuntu'
          ansible_ssh_private_key_file: '~/.ssh/nhncloud-letomok.pub'
          # ansible_ssh_pass: 'ubuntu'
        # worker_2:
        #   ansible_host: '10.0.15.9'
        #   hostname: worker-2
        #   ansible_user: 'ubuntu'
        #   ansible_ssh_private_key_file: '~/.ssh/lms-general-purpose-key.pub'
          # ansible_ssh_pass: 'ubuntu'
        # worker_3:
        #   ansible_host: '10.1.59.185'
        #   hostname: worker-3
        #   ansible_user: 'ubuntu'
        #   ansible_ssh_private_key_file: '~/.ssh/lms-general-purpose-key.pub'
        #   # ansible_ssh_pass: 'ubuntu'